### ISSUE TITLE
Build error after update to 5.0.4

### ISSUE THREAD

**Issue by FaraFara** [typographist/postcss#92]
I am using webpack with postcss.config.js for build bundle.
After update to 5.0.4 got this error:
`TypeError: Cannot read property 'MINOR_SECOND' of undefined`
`TypeError: typographist is not a function`

postcss.config.js:
```
const { typographist, ratios } = require('@typographist/postcss');

module.exports = () => ({
    plugins: [
        require('postcss-preset-env')({
            stage: 3,
            features: {
                'nesting-rules': true,
                'custom-media-queries': true,
                'custom-selectors': true,
            },
            autoprefixer: {
                grid: true
            }
        }),
        typographist({
            base: '16px',
            lineHeight: 1.4,
            ratio: ratios.MINOR_SECOND,
            sm: {
                breakpoint: '576px',
                base: '16px',
                ratio: ratios.MAJOR_SECOND,
            },
            md: {
                breakpoint: '768px',
                base: '17px',
                ratio: ratios.MAJOR_SECOND,
            },
            lg: {
                breakpoint: '992px',
                base: '19px',
                ratio: ratios.MINOR_THIRD,
            },
            xl: {
                breakpoint: '1200px',
                base: '21px',
            },
        }),
    ],
});
```

5.0.3 work fine.
What's wrong?

**Comment by mg901** [comment]
@FaraFara, Hi!, Until I understood what was happening, use version 5.3. In the coming week I will correct these errors and write to you about it.

**Comment by mg901** [comment]
@FaraFara, Try to upgrade to the latest version. Does everything work?

**Comment by FaraFara** [comment]
@mg901, Hi! All works again! Thanx!
